version: "3"
services:
  kademliaNodes:
    image: test:latest
    stdin_open: true
    tty: true
    environment:
      - BASENODE=0
    deploy:
      replicas: 100 
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
  baseNode:
    image: test:latest
    stdin_open: true
    tty: true
    environment:
      - BASENODE=1
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure 
    networks:
      - kademlia_network
  serverNode:
            image: server:latest
            stdin_open: true
            tty: true
            deploy:
              replicas: 1
            ports:
              - "8001:8001"
            networks:
              - kademlia_network    
networks:
  kademlia_network:
