// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademlia.proto

package protobuf

import (
	fmt "fmt"
	proto "proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KMessage struct {
	SndrID               string   `protobuf:"bytes,1,opt,name=sndrID,proto3" json:"sndrID,omitempty"`
	SndrAddress          string   `protobuf:"bytes,2,opt,name=sndrAddress,proto3" json:"sndrAddress,omitempty"`
	MsgType              string   `protobuf:"bytes,3,opt,name=msgType,proto3" json:"msgType,omitempty"`
	RcvrID               string   `protobuf:"bytes,4,opt,name=rcvrID,proto3" json:"rcvrID,omitempty"`
	RcvrAddress          string   `protobuf:"bytes,5,opt,name=rcvrAddress,proto3" json:"rcvrAddress,omitempty"`
	Dist                 string   `protobuf:"bytes,6,opt,name=dist,proto3" json:"dist,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Key                  string   `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	Val                  string   `protobuf:"bytes,9,opt,name=val,proto3" json:"val,omitempty"`
	Contacts             []string `protobuf:"bytes,10,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KMessage) Reset()         { *m = KMessage{} }
func (m *KMessage) String() string { return proto.CompactTextString(m) }
func (*KMessage) ProtoMessage()    {}
func (*KMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_79477522ae6a503a, []int{0}
}

func (m *KMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KMessage.Unmarshal(m, b)
}
func (m *KMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KMessage.Marshal(b, m, deterministic)
}
func (m *KMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KMessage.Merge(m, src)
}
func (m *KMessage) XXX_Size() int {
	return xxx_messageInfo_KMessage.Size(m)
}
func (m *KMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KMessage proto.InternalMessageInfo

func (m *KMessage) GetSndrID() string {
	if m != nil {
		return m.SndrID
	}
	return ""
}

func (m *KMessage) GetSndrAddress() string {
	if m != nil {
		return m.SndrAddress
	}
	return ""
}

func (m *KMessage) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *KMessage) GetRcvrID() string {
	if m != nil {
		return m.RcvrID
	}
	return ""
}

func (m *KMessage) GetRcvrAddress() string {
	if m != nil {
		return m.RcvrAddress
	}
	return ""
}

func (m *KMessage) GetDist() string {
	if m != nil {
		return m.Dist
	}
	return ""
}

func (m *KMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *KMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KMessage) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *KMessage) GetContacts() []string {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func init() {
	proto.RegisterType((*KMessage)(nil), "protobuf.kMessage")
}

func init() { proto.RegisterFile("kademlia.proto", fileDescriptor_79477522ae6a503a) }

var fileDescriptor_79477522ae6a503a = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xa6, 0xa4, 0xce, 0x81, 0x10, 0xba, 0x01, 0x9d, 0x98, 0x2c, 0xa6, 0x4c, 0x2c,
	0x3c, 0x01, 0x12, 0x0b, 0x03, 0x4b, 0xc4, 0x0b, 0x5c, 0x63, 0x53, 0x55, 0x49, 0x9b, 0xca, 0x67,
	0x22, 0x65, 0xe3, 0xd1, 0x91, 0xcf, 0xa4, 0xca, 0xe4, 0xff, 0xff, 0x7e, 0xeb, 0x1b, 0x0e, 0xee,
	0x7b, 0x76, 0xfe, 0x34, 0x1c, 0xf9, 0xe5, 0x12, 0xc6, 0x38, 0xa2, 0xd1, 0x67, 0xff, 0xf3, 0xfd,
	0xfc, 0xbb, 0x01, 0xd3, 0x7f, 0x7a, 0x11, 0x3e, 0x78, 0x7c, 0x84, 0x4a, 0xce, 0x2e, 0x7c, 0xbc,
	0x53, 0x61, 0x8b, 0xa6, 0x6e, 0xff, 0x1b, 0x5a, 0xb8, 0x4d, 0xe9, 0xcd, 0xb9, 0xe0, 0x45, 0x68,
	0xa3, 0xe3, 0x1a, 0x21, 0xc1, 0xee, 0x24, 0x87, 0xaf, 0xf9, 0xe2, 0xa9, 0xd4, 0x75, 0xa9, 0xc9,
	0x19, 0xba, 0x29, 0x39, 0xb7, 0xd9, 0x99, 0x5b, 0x72, 0xa6, 0xb4, 0x38, 0x6f, 0xb2, 0x73, 0x85,
	0x10, 0x61, 0xeb, 0x8e, 0x12, 0xa9, 0xd2, 0x49, 0xb3, 0x32, 0x8e, 0x4c, 0x3b, 0x5b, 0x34, 0x77,
	0xad, 0x66, 0x7c, 0x80, 0xb2, 0xf7, 0x33, 0x19, 0xfd, 0x96, 0x62, 0x22, 0x13, 0x0f, 0x54, 0x67,
	0x32, 0xf1, 0x80, 0x4f, 0x60, 0xba, 0xf1, 0x1c, 0xb9, 0x8b, 0x42, 0x60, 0xcb, 0xa6, 0x6e, 0xaf,
	0x7d, 0x5f, 0xe9, 0x31, 0x5e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xc4, 0xd1, 0x46, 0x25,
	0x01, 0x00, 0x00,
}
