// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademlia.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KMessage struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	SndrAddress          string   `protobuf:"bytes,2,opt,name=sndrAddress,proto3" json:"sndrAddress,omitempty"`
	SndrID               string   `protobuf:"bytes,3,opt,name=sndrID,proto3" json:"sndrID,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KMessage) Reset()         { *m = KMessage{} }
func (m *KMessage) String() string { return proto.CompactTextString(m) }
func (*KMessage) ProtoMessage()    {}
func (*KMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_79477522ae6a503a, []int{0}
}

func (m *KMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KMessage.Unmarshal(m, b)
}
func (m *KMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KMessage.Marshal(b, m, deterministic)
}
func (m *KMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KMessage.Merge(m, src)
}
func (m *KMessage) XXX_Size() int {
	return xxx_messageInfo_KMessage.Size(m)
}
func (m *KMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KMessage proto.InternalMessageInfo

func (m *KMessage) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *KMessage) GetSndrAddress() string {
	if m != nil {
		return m.SndrAddress
	}
	return ""
}

func (m *KMessage) GetSndrID() string {
	if m != nil {
		return m.SndrID
	}
	return ""
}

func (m *KMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type KMessageLookupContact struct {
	RcvrAddress          string   `protobuf:"bytes,4,opt,name=rcvrAddress,proto3" json:"rcvrAddress,omitempty"`
	RcvrID               string   `protobuf:"bytes,5,opt,name=rcvrID,proto3" json:"rcvrID,omitempty"`
	Dist                 string   `protobuf:"bytes,6,opt,name=dist,proto3" json:"dist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KMessageLookupContact) Reset()         { *m = KMessageLookupContact{} }
func (m *KMessageLookupContact) String() string { return proto.CompactTextString(m) }
func (*KMessageLookupContact) ProtoMessage()    {}
func (*KMessageLookupContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_79477522ae6a503a, []int{0, 0}
}

func (m *KMessageLookupContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KMessageLookupContact.Unmarshal(m, b)
}
func (m *KMessageLookupContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KMessageLookupContact.Marshal(b, m, deterministic)
}
func (m *KMessageLookupContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KMessageLookupContact.Merge(m, src)
}
func (m *KMessageLookupContact) XXX_Size() int {
	return xxx_messageInfo_KMessageLookupContact.Size(m)
}
func (m *KMessageLookupContact) XXX_DiscardUnknown() {
	xxx_messageInfo_KMessageLookupContact.DiscardUnknown(m)
}

var xxx_messageInfo_KMessageLookupContact proto.InternalMessageInfo

func (m *KMessageLookupContact) GetRcvrAddress() string {
	if m != nil {
		return m.RcvrAddress
	}
	return ""
}

func (m *KMessageLookupContact) GetRcvrID() string {
	if m != nil {
		return m.RcvrID
	}
	return ""
}

func (m *KMessageLookupContact) GetDist() string {
	if m != nil {
		return m.Dist
	}
	return ""
}

func init() {
	proto.RegisterType((*KMessage)(nil), "protobuf.kMessage")
	proto.RegisterType((*KMessageLookupContact)(nil), "protobuf.kMessage.lookupContact")
}

func init() { proto.RegisterFile("kademlia.proto", fileDescriptor_79477522ae6a503a) }

var fileDescriptor_79477522ae6a503a = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4e, 0x4c, 0x49,
	0xcd, 0xcd, 0xc9, 0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5,
	0x69, 0x4a, 0x17, 0x19, 0xb9, 0x38, 0xb2, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x24,
	0xb8, 0xd8, 0x73, 0x8b, 0xd3, 0x43, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x60, 0x5c, 0x21, 0x05, 0x2e, 0xee, 0xe2, 0xbc, 0x94, 0x22, 0xc7, 0x94, 0x94, 0xa2, 0xd4, 0xe2,
	0x62, 0x09, 0x26, 0xb0, 0x2c, 0xb2, 0x90, 0x90, 0x18, 0x17, 0x1b, 0x88, 0xeb, 0xe9, 0x22, 0xc1,
	0x0c, 0x96, 0x84, 0xf2, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0xd8, 0x15, 0x18,
	0x35, 0x78, 0x82, 0xc0, 0x6c, 0xa9, 0x58, 0x2e, 0xde, 0x9c, 0xfc, 0xfc, 0xec, 0xd2, 0x02, 0xe7,
	0xfc, 0xbc, 0x92, 0xc4, 0xe4, 0x12, 0x90, 0xf1, 0x45, 0xc9, 0x65, 0x70, 0xe3, 0x59, 0x20, 0xc6,
	0x23, 0x09, 0x81, 0x8c, 0x07, 0x71, 0x3d, 0x5d, 0x24, 0x58, 0x21, 0xc6, 0x43, 0x78, 0x60, 0xe3,
	0x33, 0x8b, 0x4b, 0x24, 0xd8, 0xc0, 0xa2, 0x60, 0x76, 0x12, 0x1b, 0xd8, 0x77, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x03, 0x90, 0xb8, 0x29, 0xf6, 0x00, 0x00, 0x00,
}
